bundler_args: --without documentation
script: bundle exec rake compile test
env:
  global:
    - TESTOPTS=-v
language: ruby
sudo: false
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx
  - jruby-1.7
  - jruby-9
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-1.7
    - rvm: jruby-9
  include:
    - rvm: 2.0.0
      os: osx
